fix(light): print an err if trusted store is empty (#4004)
```
E[2024-09-04|08:30:08.839] Cannot start the light client from an empty trusted store. Please provide either an initialized trusted store, using the `--home-dir` flag, or trusted information to bootstrap the trusted store, via `--hash` and `--height` flags.
ERROR: trusted store is empty
```

Refs #3992

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use
[unclog](https://github.com/informalsystems/unclog) to manage our
changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code
comments

---------

Co-authored-by: Daniel <daniel.cason@informal.systems>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
(cherry picked from commit 18786e157271d84b08122cdddb2bd26f4601a12b)

# Conflicts:
#	light/client.go
#	light/errors.go